name: rotation
description: Provide easy features to produce transform behaviours.
version: 0.0.2
homepage: https://github.com/jrlisboa/rotation
documentation: https://github.com/jrlisboa/rotation
repository: https://github.com/jrlisboa/rotation

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: